# Generated by Django 4.2.11 on 2024-04-24 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(default='', max_length=50, verbose_name='회원명')),
                ('phone', models.CharField(default='', max_length=30, verbose_name='전화번호')),
                ('birth', models.DateField(null=True, verbose_name='생년월일')),
                ('withdrawal_at', models.DateTimeField(null=True, verbose_name='탈퇴일')),
                ('email_verified', models.BooleanField(default=False, verbose_name='이메일 인증여부')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_profile',
            },
        ),
    ]
