# Generated by Django 4.2.11 on 2024-04-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(default='', max_length=50, verbose_name='회사'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='membername',
            field=models.CharField(default='', max_length=100, verbose_name='회원명'),
        ),
    ]
