# Generated by Django 4.2.11 on 2024-05-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile_company_alter_profile_membername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('is_activate', models.BooleanField(default=True, verbose_name='활성화여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초구독일')),
            ],
            options={
                'db_table': 'subscriber',
            },
        ),
    ]
