# Generated by Django 4.2.11 on 2024-07-18 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_tag_blogtag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogtag",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_tag",
                to="website.blog",
            ),
        ),
    ]
